/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.text.*;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Anthony
 */
public class FormularioAlquiler extends javax.swing.JFrame {

    private int codigo_alquiler=500;
    Vector vec_alq=new Vector();
    /**
     * Creates new form FormularioArquiler
     */
    public FormularioAlquiler() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(100, 300, 1300, 630);
        setLocationRelativeTo(null);
        //
        
        int i;
    	
    	Vector va = new Vector(15,2);
    	Sistema s= new Sistema();
    	s.escribeFicheroAgencia();
    	va= s.leeFicheroAgencia();
    	
    
        
    	Vector vg = new Vector(15,2);
    	s.escribeFicheroGarage();
    	vg= s.leeFicheroGarage();
    	
    	Vector vv = new Vector(15,2);
    	s.escribeFicheroVehiculo();
    	vv= s.leeFicheroVehiculo();
    	
    	Vector vc = new Vector(15,2);
    	s.escribeFicheroCliente();
    	vc= s.leeFicheroCliente();
    	
    	
    	Vector vu = new Vector(15,2);
    	s.escribeFicheroUsuario();
    	vu= s.leeFicheroUsuario();
    	
    	/*
        Agencia [] p;
        p = new Agencia[v.size()];
        for(i=0;i<v.size();i++)
        {
        	p[i]= (Agencia)v.elementAt(i);
        }
        System.out.println("la agencia 5 es "+p[5].getNombre_age());
		*/
		
		//
                
        //public int codigo_alquiler=500;
         
        
        Vector vec1 = new Vector();
        Prueba prueba1;
        
        //modelo.addElement(new Prueba("Anthony",1));
        //modelo.addElement(new Prueba("Johnny",2));
        
        vec1.add(new Prueba("Anthony",1));
        vec1.add(new Prueba("Johnny",2));
        
        
        //CASTEO 1er COMBO BOX
        for (i=0 ; i<va.size() ; i++)
        {    
            Agencia ag1 = (Agencia)va.elementAt(i);
            jComboBox4.addItem(ag1.getNombre_age().toString());
        }   
        
        //CASTEO 2DO COMBO BOX
        for (i=0 ; i<vv.size() ; i++)
        {   
            Vehiculo ve1 = (Vehiculo)vv.elementAt(i);
            if(ve1.isEstado_veh())
                jComboBox3.addItem(ve1.getMatricula_veh().toString());
        }   
        
        //CASTEO 3er COMBO BOX
        for (i=0 ; i<vc.size() ; i++)
        {    
            Cliente cli1 = (Cliente)vc.elementAt(i);
            jComboBox1.addItem(cli1.getNombre_per().toString());
        }   
        
        //CASTEO 4er COMBO BOX
        for (i=0 ; i<vu.size() ; i++)
        {    
            Usuario usu1 = (Usuario)vu.elementAt(i);
            jComboBox2.addItem(usu1.getNombre_per().toString());
        }   
        
        //jComboBox1.addItem(vec1.toString());
        
        //JComboBox combobox5 = new JComboBox(vec1);
        //jComboBox1=new JComboBox(vec1);
        
        //private String vehiculo = jComboBox1.getSelectedItem().toString
        //private String agencia = jComboBox2.getSelectedItem().toString
        //private String cliente = jComboBox3.getSelectedItem().toString
        
        //
    

                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setName(""); // NOI18N
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(520, 110, 150, 28);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(520, 160, 150, 28);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(520, 210, 150, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cliente:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 110, 110, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 160, 120, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehículo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 200, 130, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("ALQUILER DE VEHÍCULO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 20, 440, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Complete la información para procesar el pedido de arquiler.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 70, 540, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agencia:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 250, 120, 29);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(520, 250, 150, 28);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 370, 120, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de inicio:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 280, 180, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de fin:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 310, 160, 29);

        jFormattedTextField1.setText("yyyy-mm-dd");
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(520, 290, 150, 30);

        jFormattedTextField2.setText("yyyy-mm-dd");
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(520, 330, 150, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(710, 370, 140, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 370, 140, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantallaAlquilerMSD.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 860, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int indiceVehiculo=jComboBox3.getSelectedIndex();
        int indiceAgencia=jComboBox4.getSelectedIndex();
        int indiceUsuario=jComboBox2.getSelectedIndex();
        int indiceCliente=jComboBox1.getSelectedIndex();
        
        String fecha_inicio = jFormattedTextField1.getText();
        String fecha_fin =jFormattedTextField1.getText();
        System.out.println("1:"+fecha_inicio+" + "+fecha_fin);
        
        int i;
    	
    	Vector va = new Vector(15,2);
    	Sistema s= new Sistema();
    	s.escribeFicheroAgencia();
    	va= s.leeFicheroAgencia();
    	
    
        
    	Vector vg = new Vector(15,2);
    	s.escribeFicheroGarage();
    	vg= s.leeFicheroGarage();
    	
    	Vector vv = new Vector(15,2);
    	s.escribeFicheroVehiculo();
    	vv= s.leeFicheroVehiculo();
    	
    	Vector vc = new Vector(15,2);
    	s.escribeFicheroCliente();
    	vc= s.leeFicheroCliente();
    	
    	
    	Vector vu = new Vector(15,2);
    	s.escribeFicheroUsuario();
    	vu= s.leeFicheroUsuario();
        
        Pantalla1 menu = new Pantalla1();
        setVisible(false);
        menu.setVisible(true);
       
        Agencia ag1 = (Agencia) va.elementAt(indiceAgencia);
        Cliente cli1=(Cliente)vc.elementAt(indiceCliente);
        Usuario usu1=(Usuario)vu.elementAt(indiceUsuario);
        Vehiculo veh1=(Vehiculo)vv.elementAt(indiceVehiculo);
        
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        Date t=new Date();
        Date u =new Date();
        try{
            t=ft.parse(fecha_inicio);
            u=ft.parse(fecha_fin);
        }catch(ParseException e){
            System.out.println("Error de casteo");
        }      
               
                    

        
        Alquiler alquiler1 = new Alquiler(this.codigo_alquiler,cli1.getCod_per(), usu1.getCod_per(), 
                veh1.getCodigo_veh(), ag1.getCodigo_age(), t, u, veh1.getPrecio_veh());
        this.codigo_alquiler++;
        
        
        System.out.println("Se acabó de alquilar");
        
        if(vec_alq.isEmpty())
        {
          vec_alq.add(alquiler1);
        } 
        else
        {
            i =vec_alq.size();
            vec_alq.add(i,alquiler1);
            System.out.println(i);
        }
        try
	        {
	            ObjectOutputStream oos = new ObjectOutputStream(
	            new FileOutputStream("L:/Alquiler.dat",true));
	            
	            oos.writeObject(alquiler1);
	            
	            oos.close();
	        } catch (Exception e)
	        {
	            e.printStackTrace();
	        }
        /*try {
	       // PrintWriter pw = new PrintWriter( new File("L:/alquileres.txt") );
                
                
	        
                    
                    
                    System.out.println(i);
                    pw.println(alquiler1.);
                    pw.flush();
                    
                    
                      pw.close();
	}

	    } catch (IOException ioe ) { ioe.printStackTrace(); }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Vector v = new Vector(15,2);
        try
        {
            // Se crea un ObjectInputStream
            ObjectInputStream ois = new ObjectInputStream(
                    new FileInputStream("L:/Alquiler.dat"));
            
            // Se lee el primer objeto
            Object aux = ois.readObject();
            v.addElement(aux);
            // Mientras haya objetos
            while (aux!=null)
            {
                if (aux instanceof Alquiler)
                {
                    aux = ois.readObject();
                    System.out.println(aux);
                    v.addElement(aux);
                }
                
            }
            ois.close();
        }
        catch (EOFException e1)
        {
            System.out.println ("Agencias cargadas");
        }
        catch (Exception e2)
        {
            e2.printStackTrace();
        }
     
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
